"""
add status to exam_sessions

Revision ID: a3655395a289
Revises: 1f07b9f762a
Create Date: 2026-10-04 16:17:49.066004+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3655395a289'
down_revision = '1f07b9f762a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('slot_bookings', 'cancelled_at')
    op.add_column('slots', sa.Column('date', sa.Date(), nullable=True))
    op.alter_column('slots', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('slots', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    op.drop_constraint(op.f('slots_level_id_fkey'), 'slots', type_='foreignkey')
    op.drop_column('slots', 'level_id')
    op.drop_column('slots', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('slots', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('slots_level_id_fkey'), 'slots', 'levels', ['level_id'], ['id'])
    op.alter_column('slots', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('slots', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('slots', 'date')
    op.add_column('slot_bookings', sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('exam_sessions', 'status')
    # ### end Alembic commands ###
